DEBUG = False
IMG_ROOT = 'static/imgs/'
TIMELIMIT = 600

# status codes
NOT_LOGIN = 'NOT_LOGIN'
GET_SUCCESS = 'GET_SUCCESS'
NAME_PASSWORD_WRONG = 'NAME_PASSWORD_WRONG'
NAME_NULL = 'NAME_NULL'
PASSWORD_NULL = 'PASSWORD_NULL'
LOGIN_EXPIRED = 'LOGIN_EXPIRED'
LOGINOUT_UNKNOWN = 'LOGINOUT_UNKNOWN'
LIMIT_EXCEEDED = 'LIMIT_EXCEEDED'

REGISTER_SUCCESS = 'REGISTER_SUCCESS'
REGISTER_FAIL = 'REGISTER_FAIL'
NO_REPEAT = 'NO_REPEAT'

LIKE_SUCCESS = 'LIKE_SUCCESS'
LIKE_FAILED = 'LIKE_FAILED'

POST_SUCCESS = 'POST_SUCCESS'
TITLE_NULL = 'TITLE_NULL'
POST_DELETED = 'POST_DELETED'
POST_UNEXIST = 'POST_UNEXIST'
POST_NO_AUTHORIZE = 'POST_NO_AUTHORIZE'
POST_UNKNOWN = 'POST_UNKNOWN'

REPLY_SUCCESS = 'REPLY_SUCCESS'
CONTENT_NULL = 'CONTENT_NULL'
REPLY_DELETED = 'REPLY_DELETED'
REPLY_UNEXIST = 'REPLY_UNEXIST'
REPLY_NO_AUTHORIZE = 'REPLY_NO_AUTHORIZE'
REPLY_UNKNOWN = 'REPLY_UNKNOWN'

MERGE_SUCCESS = 'MERGE_SUCCESS'
MERGE_FAILED = 'MERGE_FAILED'

MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
MESSAGE_FAILED = 'MESSAGE_FAILED'

NOTICE_SUCCESS = 'NOTICE_SUCCESS'
NOTICE_FAILED = 'NOTICE_FAILED'
NOTICE_NO_AUTHORIZE = 'NOTICE_NO_AUTHORIZE'

SET_SUCCESS = 'SET_SUCCESS'
SET_FAILED = 'SET_FAILED'

IMAGE_NULL = 'IMAGE_NULL'
IMAGE_OVERSIZE = 'IMAGE_OVERSIZE'
IMAGE_SUCCESS = 'IMAGE_SUCCESS'
IMAGE_FAILED = 'IMAGE_FAILED'

SEARCH_SUCCESS = 'SEARCH_SUCCESS'
SEARCH_FAILED = 'SEARCH_FAILED'
SEARCH_EMPTY = 'SEARCH_EMPTY'
